copter_arm:
  state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50

  free_controller:
     type: effort_controllers/JointEffortController
     joint: free_joint

  motor_controller:
     type: velocity_controllers/JointVelocityController
     joint: motor_joint
     # pid: {p: 10.0,  i: 0.0, d: 0.0, i_clamp: 5}
